version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    # 其他 client 配置 ...

  server:
    build: ./server
    ports:
      - "8080:8080"
    # 其他 server 配置 ...

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: [--auth]

volumes:
  mongodb-data:
    driver: local