# 使用官方 Node.js 基础镜像
FROM node:16

# 设置工作目录
WORKDIR /usr/src/app

# 将 package.json 和 package-lock.json 复制到工作目录
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 将源代码复制到工作目录
COPY . .

# 设置环境变量
ENV PORT 8080

# 暴露端口 8080
EXPOSE 8080

# 定义运行时的命令
CMD ["node", "server.js"]
